##This script processes disparate data files related to a the UCI Har project
##into one tidy dataset and then summarizes all the mean and standard deviation 
##variables to generate one final output tidy dataset

##Read in all the data files into data tables
		datXTrain <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/train/X_train.txt')
		datYTrain <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/train/y_train.txt')
		datXTest <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/test/X_test.txt')
		datYTest <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/test/y_test.txt')
    datSubjectTrain <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/train/subject_train.txt')
		datSubjectTest <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/test/subject_test.txt')
		datActivityLabels <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/activity_labels.txt')
		datFeatures <- read.table('C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/features.txt')    
    
##Union together all the rows for the Testing and Training databases    
		datXRows <- rbind(datXTest, datXTrain)
		datSubjectRows <- rbind(datSubjectTest, datSubjectTrain)
		datYRows <- rbind(datYTest, datYTrain)

##Update the column names to be real column names and not V1    
		colnames(datSubjectRows)[colnames(datSubjectRows) == "V1"] <- "Subject"
		colnames(datYRows)[colnames(datYRows) == "V1"] <- "ActivityId"       
    
#     head(datXRows)
# 		head(datSubjectRows)
#     head(datYRows)
#     nrow(datYRows)
    
##Update the column names within the activity lables data table so that they are easier to work with		
    colnames(datActivityLabels)[colnames(datActivityLabels) == "V1"] <- "ActivityId"        
		colnames(datActivityLabels)[colnames(datActivityLabels) == "V2"] <- "ActivityName"

##Merge the columns for the separate data tables containing the aligned data rows
		datMerge <- cbind(datXRows, datSubjectRows, datYRows)
    
    ##colnames(datMerge)
    ##head(datMerge)
    ##nrow(datMerge)

##Update all the column names for the measurement variables so that they are more descriptive    
    
		colnames(datMerge)[colnames(datMerge) == "V1"] <- "tBodyAccMeanX"
		colnames(datMerge)[colnames(datMerge) == "V2"] <- "tBodyAccMeanY"
		colnames(datMerge)[colnames(datMerge) == "V3"] <- "tBodyAccMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V4"] <- "tBodyAccStdX"
		colnames(datMerge)[colnames(datMerge) == "V5"] <- "tBodyAccStdY"
		colnames(datMerge)[colnames(datMerge) == "V6"] <- "tBodyAccStdZ"
		colnames(datMerge)[colnames(datMerge) == "V7"] <- "tBodyAccMadX"
		colnames(datMerge)[colnames(datMerge) == "V8"] <- "tBodyAccMadY"
		colnames(datMerge)[colnames(datMerge) == "V9"] <- "tBodyAccMadZ"
		colnames(datMerge)[colnames(datMerge) == "V10"] <- "tBodyAccMaxX"
		colnames(datMerge)[colnames(datMerge) == "V11"] <- "tBodyAccMaxY"
		colnames(datMerge)[colnames(datMerge) == "V12"] <- "tBodyAccMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V13"] <- "tBodyAccMinX"
		colnames(datMerge)[colnames(datMerge) == "V14"] <- "tBodyAccMinY"
		colnames(datMerge)[colnames(datMerge) == "V15"] <- "tBodyAccMinZ"
		colnames(datMerge)[colnames(datMerge) == "V16"] <- "tBodyAccSma"
		colnames(datMerge)[colnames(datMerge) == "V17"] <- "tBodyAccEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V18"] <- "tBodyAccEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V19"] <- "tBodyAccEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V20"] <- "tBodyAccIQRX"
		colnames(datMerge)[colnames(datMerge) == "V21"] <- "tBodyAccIQRY"
		colnames(datMerge)[colnames(datMerge) == "V22"] <- "tBodyAccIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V23"] <- "tBodyAccEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V24"] <- "tBodyAccEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V25"] <- "tBodyAccEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V26"] <- "tBodyAccArCoeffX_1"
		colnames(datMerge)[colnames(datMerge) == "V27"] <- "tBodyAccArCoeffX_2"
		colnames(datMerge)[colnames(datMerge) == "V28"] <- "tBodyAccArCoeffX_3"
		colnames(datMerge)[colnames(datMerge) == "V29"] <- "tBodyAccArCoeffX_4"
		colnames(datMerge)[colnames(datMerge) == "V30"] <- "tBodyAccArCoeffY_1"
		colnames(datMerge)[colnames(datMerge) == "V31"] <- "tBodyAccArCoeffY_2"
		colnames(datMerge)[colnames(datMerge) == "V32"] <- "tBodyAccArCoeffY_3"
		colnames(datMerge)[colnames(datMerge) == "V33"] <- "tBodyAccArCoeffY_4"
		colnames(datMerge)[colnames(datMerge) == "V34"] <- "tBodyAccArCoeffZ_1"
		colnames(datMerge)[colnames(datMerge) == "V35"] <- "tBodyAccArCoeffZ_2"
		colnames(datMerge)[colnames(datMerge) == "V36"] <- "tBodyAccArCoeffZ_3"
		colnames(datMerge)[colnames(datMerge) == "V37"] <- "tBodyAccArCoeffZ_4"
		colnames(datMerge)[colnames(datMerge) == "V38"] <- "tBodyAccCorrelationX_Y"
		colnames(datMerge)[colnames(datMerge) == "V39"] <- "tBodyAccCorrelationX_Z"
		colnames(datMerge)[colnames(datMerge) == "V40"] <- "tBodyAccCorrelationY_Z"
		colnames(datMerge)[colnames(datMerge) == "V41"] <- "tGravityAccMeanX"
		colnames(datMerge)[colnames(datMerge) == "V42"] <- "tGravityAccMeanY"
		colnames(datMerge)[colnames(datMerge) == "V43"] <- "tGravityAccMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V44"] <- "tGravityAccStdX"
		colnames(datMerge)[colnames(datMerge) == "V45"] <- "tGravityAccStdY"
		colnames(datMerge)[colnames(datMerge) == "V46"] <- "tGravityAccStdZ"
		colnames(datMerge)[colnames(datMerge) == "V47"] <- "tGravityAccMadX"
		colnames(datMerge)[colnames(datMerge) == "V48"] <- "tGravityAccMadY"
		colnames(datMerge)[colnames(datMerge) == "V49"] <- "tGravityAccMadZ"
		colnames(datMerge)[colnames(datMerge) == "V50"] <- "tGravityAccMaxX"
		colnames(datMerge)[colnames(datMerge) == "V51"] <- "tGravityAccMaxY"
		colnames(datMerge)[colnames(datMerge) == "V52"] <- "tGravityAccMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V53"] <- "tGravityAccMinX"
		colnames(datMerge)[colnames(datMerge) == "V54"] <- "tGravityAccMinY"
		colnames(datMerge)[colnames(datMerge) == "V55"] <- "tGravityAccMinZ"
		colnames(datMerge)[colnames(datMerge) == "V56"] <- "tGravityAccSma"
		colnames(datMerge)[colnames(datMerge) == "V57"] <- "tGravityAccEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V58"] <- "tGravityAccEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V59"] <- "tGravityAccEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V60"] <- "tGravityAccIQRX"
		colnames(datMerge)[colnames(datMerge) == "V61"] <- "tGravityAccIQRY"
		colnames(datMerge)[colnames(datMerge) == "V62"] <- "tGravityAccIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V63"] <- "tGravityAccEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V64"] <- "tGravityAccEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V65"] <- "tGravityAccEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V66"] <- "tGravityAccArCoeffX_1"
		colnames(datMerge)[colnames(datMerge) == "V67"] <- "tGravityAccArCoeffX_2"
		colnames(datMerge)[colnames(datMerge) == "V68"] <- "tGravityAccArCoeffX_3"
		colnames(datMerge)[colnames(datMerge) == "V69"] <- "tGravityAccArCoeffX_4"
		colnames(datMerge)[colnames(datMerge) == "V70"] <- "tGravityAccArCoeffY_1"
		colnames(datMerge)[colnames(datMerge) == "V71"] <- "tGravityAccArCoeffY_2"
		colnames(datMerge)[colnames(datMerge) == "V72"] <- "tGravityAccArCoeffY_3"
		colnames(datMerge)[colnames(datMerge) == "V73"] <- "tGravityAccArCoeffY_4"
		colnames(datMerge)[colnames(datMerge) == "V74"] <- "tGravityAccArCoeffZ_1"
		colnames(datMerge)[colnames(datMerge) == "V75"] <- "tGravityAccArCoeffZ_2"
		colnames(datMerge)[colnames(datMerge) == "V76"] <- "tGravityAccArCoeffZ_3"
		colnames(datMerge)[colnames(datMerge) == "V77"] <- "tGravityAccArCoeffZ_4"
		colnames(datMerge)[colnames(datMerge) == "V78"] <- "tGravityAccCorrelationX_Y"
		colnames(datMerge)[colnames(datMerge) == "V79"] <- "tGravityAccCorrelationX_Z"
		colnames(datMerge)[colnames(datMerge) == "V80"] <- "tGravityAccCorrelationY_Z"
		colnames(datMerge)[colnames(datMerge) == "V81"] <- "tBodyAccJerkMeanX"
		colnames(datMerge)[colnames(datMerge) == "V82"] <- "tBodyAccJerkMeanY"
		colnames(datMerge)[colnames(datMerge) == "V83"] <- "tBodyAccJerkMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V84"] <- "tBodyAccJerkStdX"
		colnames(datMerge)[colnames(datMerge) == "V85"] <- "tBodyAccJerkStdY"
		colnames(datMerge)[colnames(datMerge) == "V86"] <- "tBodyAccJerkStdZ"
		colnames(datMerge)[colnames(datMerge) == "V87"] <- "tBodyAccJerkMadX"
		colnames(datMerge)[colnames(datMerge) == "V88"] <- "tBodyAccJerkMadY"
		colnames(datMerge)[colnames(datMerge) == "V89"] <- "tBodyAccJerkMadZ"
		colnames(datMerge)[colnames(datMerge) == "V90"] <- "tBodyAccJerkMaxX"
		colnames(datMerge)[colnames(datMerge) == "V91"] <- "tBodyAccJerkMaxY"
		colnames(datMerge)[colnames(datMerge) == "V92"] <- "tBodyAccJerkMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V93"] <- "tBodyAccJerkMinX"
		colnames(datMerge)[colnames(datMerge) == "V94"] <- "tBodyAccJerkMinY"
		colnames(datMerge)[colnames(datMerge) == "V95"] <- "tBodyAccJerkMinZ"
		colnames(datMerge)[colnames(datMerge) == "V96"] <- "tBodyAccJerkSma"
		colnames(datMerge)[colnames(datMerge) == "V97"] <- "tBodyAccJerkEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V98"] <- "tBodyAccJerkEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V99"] <- "tBodyAccJerkEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V100"] <- "tBodyAccJerkIQRX"
		colnames(datMerge)[colnames(datMerge) == "V101"] <- "tBodyAccJerkIQRY"
		colnames(datMerge)[colnames(datMerge) == "V102"] <- "tBodyAccJerkIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V103"] <- "tBodyAccJerkEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V104"] <- "tBodyAccJerkEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V105"] <- "tBodyAccJerkEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V106"] <- "tBodyAccJerkArCoeffX_1"
		colnames(datMerge)[colnames(datMerge) == "V107"] <- "tBodyAccJerkArCoeffX_2"
		colnames(datMerge)[colnames(datMerge) == "V108"] <- "tBodyAccJerkArCoeffX_3"
		colnames(datMerge)[colnames(datMerge) == "V109"] <- "tBodyAccJerkArCoeffX_4"
		colnames(datMerge)[colnames(datMerge) == "V110"] <- "tBodyAccJerkArCoeffY_1"
		colnames(datMerge)[colnames(datMerge) == "V111"] <- "tBodyAccJerkArCoeffY_2"
		colnames(datMerge)[colnames(datMerge) == "V112"] <- "tBodyAccJerkArCoeffY_3"
		colnames(datMerge)[colnames(datMerge) == "V113"] <- "tBodyAccJerkArCoeffY_4"
		colnames(datMerge)[colnames(datMerge) == "V114"] <- "tBodyAccJerkArCoeffZ_1"
		colnames(datMerge)[colnames(datMerge) == "V115"] <- "tBodyAccJerkArCoeffZ_2"
		colnames(datMerge)[colnames(datMerge) == "V116"] <- "tBodyAccJerkArCoeffZ_3"
		colnames(datMerge)[colnames(datMerge) == "V117"] <- "tBodyAccJerkArCoeffZ_4"
		colnames(datMerge)[colnames(datMerge) == "V118"] <- "tBodyAccJerkCorrelationX_Y"
		colnames(datMerge)[colnames(datMerge) == "V119"] <- "tBodyAccJerkCorrelationX_Z"
		colnames(datMerge)[colnames(datMerge) == "V120"] <- "tBodyAccJerkCorrelationY_Z"
		colnames(datMerge)[colnames(datMerge) == "V121"] <- "tBodyGyroMeanX"
		colnames(datMerge)[colnames(datMerge) == "V122"] <- "tBodyGyroMeanY"
		colnames(datMerge)[colnames(datMerge) == "V123"] <- "tBodyGyroMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V124"] <- "tBodyGyroStdX"
		colnames(datMerge)[colnames(datMerge) == "V125"] <- "tBodyGyroStdY"
		colnames(datMerge)[colnames(datMerge) == "V126"] <- "tBodyGyroStdZ"
		colnames(datMerge)[colnames(datMerge) == "V127"] <- "tBodyGyroMadX"
		colnames(datMerge)[colnames(datMerge) == "V128"] <- "tBodyGyroMadY"
		colnames(datMerge)[colnames(datMerge) == "V129"] <- "tBodyGyroMadZ"
		colnames(datMerge)[colnames(datMerge) == "V130"] <- "tBodyGyroMaxX"
		colnames(datMerge)[colnames(datMerge) == "V131"] <- "tBodyGyroMaxY"
		colnames(datMerge)[colnames(datMerge) == "V132"] <- "tBodyGyroMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V133"] <- "tBodyGyroMinX"
		colnames(datMerge)[colnames(datMerge) == "V134"] <- "tBodyGyroMinY"
		colnames(datMerge)[colnames(datMerge) == "V135"] <- "tBodyGyroMinZ"
		colnames(datMerge)[colnames(datMerge) == "V136"] <- "tBodyGyroSma"
		colnames(datMerge)[colnames(datMerge) == "V137"] <- "tBodyGyroEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V138"] <- "tBodyGyroEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V139"] <- "tBodyGyroEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V140"] <- "tBodyGyroIQRX"
		colnames(datMerge)[colnames(datMerge) == "V141"] <- "tBodyGyroIQRY"
		colnames(datMerge)[colnames(datMerge) == "V142"] <- "tBodyGyroIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V143"] <- "tBodyGyroEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V144"] <- "tBodyGyroEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V145"] <- "tBodyGyroEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V146"] <- "tBodyGyroArCoeffX_1"
		colnames(datMerge)[colnames(datMerge) == "V147"] <- "tBodyGyroArCoeffX_2"
		colnames(datMerge)[colnames(datMerge) == "V148"] <- "tBodyGyroArCoeffX_3"
		colnames(datMerge)[colnames(datMerge) == "V149"] <- "tBodyGyroArCoeffX_4"
		colnames(datMerge)[colnames(datMerge) == "V150"] <- "tBodyGyroArCoeffY_1"
		colnames(datMerge)[colnames(datMerge) == "V151"] <- "tBodyGyroArCoeffY_2"
		colnames(datMerge)[colnames(datMerge) == "V152"] <- "tBodyGyroArCoeffY_3"
		colnames(datMerge)[colnames(datMerge) == "V153"] <- "tBodyGyroArCoeffY_4"
		colnames(datMerge)[colnames(datMerge) == "V154"] <- "tBodyGyroArCoeffZ_1"
		colnames(datMerge)[colnames(datMerge) == "V155"] <- "tBodyGyroArCoeffZ_2"
		colnames(datMerge)[colnames(datMerge) == "V156"] <- "tBodyGyroArCoeffZ_3"
		colnames(datMerge)[colnames(datMerge) == "V157"] <- "tBodyGyroArCoeffZ_4"
		colnames(datMerge)[colnames(datMerge) == "V158"] <- "tBodyGyroCorrelationX_Y"
		colnames(datMerge)[colnames(datMerge) == "V159"] <- "tBodyGyroCorrelationX_Z"
		colnames(datMerge)[colnames(datMerge) == "V160"] <- "tBodyGyroCorrelationY_Z"
		colnames(datMerge)[colnames(datMerge) == "V161"] <- "tBodyGyroJerkMeanX"
		colnames(datMerge)[colnames(datMerge) == "V162"] <- "tBodyGyroJerkMeanY"
		colnames(datMerge)[colnames(datMerge) == "V163"] <- "tBodyGyroJerkMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V164"] <- "tBodyGyroJerkStdX"
		colnames(datMerge)[colnames(datMerge) == "V165"] <- "tBodyGyroJerkStdY"
		colnames(datMerge)[colnames(datMerge) == "V166"] <- "tBodyGyroJerkStdZ"
		colnames(datMerge)[colnames(datMerge) == "V167"] <- "tBodyGyroJerkMadX"
		colnames(datMerge)[colnames(datMerge) == "V168"] <- "tBodyGyroJerkMadY"
		colnames(datMerge)[colnames(datMerge) == "V169"] <- "tBodyGyroJerkMadZ"
		colnames(datMerge)[colnames(datMerge) == "V170"] <- "tBodyGyroJerkMaxX"
		colnames(datMerge)[colnames(datMerge) == "V171"] <- "tBodyGyroJerkMaxY"
		colnames(datMerge)[colnames(datMerge) == "V172"] <- "tBodyGyroJerkMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V173"] <- "tBodyGyroJerkMinX"
		colnames(datMerge)[colnames(datMerge) == "V174"] <- "tBodyGyroJerkMinY"
		colnames(datMerge)[colnames(datMerge) == "V175"] <- "tBodyGyroJerkMinZ"
		colnames(datMerge)[colnames(datMerge) == "V176"] <- "tBodyGyroJerkSma"
		colnames(datMerge)[colnames(datMerge) == "V177"] <- "tBodyGyroJerkEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V178"] <- "tBodyGyroJerkEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V179"] <- "tBodyGyroJerkEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V180"] <- "tBodyGyroJerkIQRX"
		colnames(datMerge)[colnames(datMerge) == "V181"] <- "tBodyGyroJerkIQRY"
		colnames(datMerge)[colnames(datMerge) == "V182"] <- "tBodyGyroJerkIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V183"] <- "tBodyGyroJerkEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V184"] <- "tBodyGyroJerkEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V185"] <- "tBodyGyroJerkEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V186"] <- "tBodyGyroJerkArCoeffX_1"
		colnames(datMerge)[colnames(datMerge) == "V187"] <- "tBodyGyroJerkArCoeffX_2"
		colnames(datMerge)[colnames(datMerge) == "V188"] <- "tBodyGyroJerkArCoeffX_3"
		colnames(datMerge)[colnames(datMerge) == "V189"] <- "tBodyGyroJerkArCoeffX_4"
		colnames(datMerge)[colnames(datMerge) == "V190"] <- "tBodyGyroJerkArCoeffY_1"
		colnames(datMerge)[colnames(datMerge) == "V191"] <- "tBodyGyroJerkArCoeffY_2"
		colnames(datMerge)[colnames(datMerge) == "V192"] <- "tBodyGyroJerkArCoeffY_3"
		colnames(datMerge)[colnames(datMerge) == "V193"] <- "tBodyGyroJerkArCoeffY_4"
		colnames(datMerge)[colnames(datMerge) == "V194"] <- "tBodyGyroJerkArCoeffZ_1"
		colnames(datMerge)[colnames(datMerge) == "V195"] <- "tBodyGyroJerkArCoeffZ_2"
		colnames(datMerge)[colnames(datMerge) == "V196"] <- "tBodyGyroJerkArCoeffZ_3"
		colnames(datMerge)[colnames(datMerge) == "V197"] <- "tBodyGyroJerkArCoeffZ_4"
		colnames(datMerge)[colnames(datMerge) == "V198"] <- "tBodyGyroJerkCorrelationX_Y"
		colnames(datMerge)[colnames(datMerge) == "V199"] <- "tBodyGyroJerkCorrelationX_Z"
		colnames(datMerge)[colnames(datMerge) == "V200"] <- "tBodyGyroJerkCorrelationY_Z"
		colnames(datMerge)[colnames(datMerge) == "V201"] <- "tBodyAccMagMean"
		colnames(datMerge)[colnames(datMerge) == "V202"] <- "tBodyAccMagStd"
		colnames(datMerge)[colnames(datMerge) == "V203"] <- "tBodyAccMagMad"
		colnames(datMerge)[colnames(datMerge) == "V204"] <- "tBodyAccMagMax"
		colnames(datMerge)[colnames(datMerge) == "V205"] <- "tBodyAccMagMin"
		colnames(datMerge)[colnames(datMerge) == "V206"] <- "tBodyAccMagSma"
		colnames(datMerge)[colnames(datMerge) == "V207"] <- "tBodyAccMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V208"] <- "tBodyAccMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V209"] <- "tBodyAccMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V210"] <- "tBodyAccMagArCoeff_1"
		colnames(datMerge)[colnames(datMerge) == "V211"] <- "tBodyAccMagArCoeff_2"
		colnames(datMerge)[colnames(datMerge) == "V212"] <- "tBodyAccMagArCoeff_3"
		colnames(datMerge)[colnames(datMerge) == "V213"] <- "tBodyAccMagArCoeff_4"
		colnames(datMerge)[colnames(datMerge) == "V214"] <- "tGravityAccMagMean"
		colnames(datMerge)[colnames(datMerge) == "V215"] <- "tGravityAccMagStd"
		colnames(datMerge)[colnames(datMerge) == "V216"] <- "tGravityAccMagMad"
		colnames(datMerge)[colnames(datMerge) == "V217"] <- "tGravityAccMagMax"
		colnames(datMerge)[colnames(datMerge) == "V218"] <- "tGravityAccMagMin"
		colnames(datMerge)[colnames(datMerge) == "V219"] <- "tGravityAccMagSma"
		colnames(datMerge)[colnames(datMerge) == "V220"] <- "tGravityAccMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V221"] <- "tGravityAccMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V222"] <- "tGravityAccMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V223"] <- "tGravityAccMagArCoeff_1"
		colnames(datMerge)[colnames(datMerge) == "V224"] <- "tGravityAccMagArCoeff_2"
		colnames(datMerge)[colnames(datMerge) == "V225"] <- "tGravityAccMagArCoeff_3"
		colnames(datMerge)[colnames(datMerge) == "V226"] <- "tGravityAccMagArCoeff_4"
		colnames(datMerge)[colnames(datMerge) == "V227"] <- "tBodyAccJerkMagMean"
		colnames(datMerge)[colnames(datMerge) == "V228"] <- "tBodyAccJerkMagStd"
		colnames(datMerge)[colnames(datMerge) == "V229"] <- "tBodyAccJerkMagMad"
		colnames(datMerge)[colnames(datMerge) == "V230"] <- "tBodyAccJerkMagMax"
		colnames(datMerge)[colnames(datMerge) == "V231"] <- "tBodyAccJerkMagMin"
		colnames(datMerge)[colnames(datMerge) == "V232"] <- "tBodyAccJerkMagSma"
		colnames(datMerge)[colnames(datMerge) == "V233"] <- "tBodyAccJerkMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V234"] <- "tBodyAccJerkMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V235"] <- "tBodyAccJerkMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V236"] <- "tBodyAccJerkMagArCoeff_1"
		colnames(datMerge)[colnames(datMerge) == "V237"] <- "tBodyAccJerkMagArCoeff_2"
		colnames(datMerge)[colnames(datMerge) == "V238"] <- "tBodyAccJerkMagArCoeff_3"
		colnames(datMerge)[colnames(datMerge) == "V239"] <- "tBodyAccJerkMagArCoeff_4"
		colnames(datMerge)[colnames(datMerge) == "V240"] <- "tBodyGyroMagMean"
		colnames(datMerge)[colnames(datMerge) == "V241"] <- "tBodyGyroMagStd"
		colnames(datMerge)[colnames(datMerge) == "V242"] <- "tBodyGyroMagMad"
		colnames(datMerge)[colnames(datMerge) == "V243"] <- "tBodyGyroMagMax"
		colnames(datMerge)[colnames(datMerge) == "V244"] <- "tBodyGyroMagMin"
		colnames(datMerge)[colnames(datMerge) == "V245"] <- "tBodyGyroMagSma"
		colnames(datMerge)[colnames(datMerge) == "V246"] <- "tBodyGyroMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V247"] <- "tBodyGyroMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V248"] <- "tBodyGyroMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V249"] <- "tBodyGyroMagArCoeff_1"
		colnames(datMerge)[colnames(datMerge) == "V250"] <- "tBodyGyroMagArCoeff_2"
		colnames(datMerge)[colnames(datMerge) == "V251"] <- "tBodyGyroMagArCoeff_3"
		colnames(datMerge)[colnames(datMerge) == "V252"] <- "tBodyGyroMagArCoeff_4"
		colnames(datMerge)[colnames(datMerge) == "V253"] <- "tBodyGyroJerkMagMean"
		colnames(datMerge)[colnames(datMerge) == "V254"] <- "tBodyGyroJerkMagStd"
		colnames(datMerge)[colnames(datMerge) == "V255"] <- "tBodyGyroJerkMagMad"
		colnames(datMerge)[colnames(datMerge) == "V256"] <- "tBodyGyroJerkMagMax"
		colnames(datMerge)[colnames(datMerge) == "V257"] <- "tBodyGyroJerkMagMin"
		colnames(datMerge)[colnames(datMerge) == "V258"] <- "tBodyGyroJerkMagSma"
		colnames(datMerge)[colnames(datMerge) == "V259"] <- "tBodyGyroJerkMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V260"] <- "tBodyGyroJerkMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V261"] <- "tBodyGyroJerkMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V262"] <- "tBodyGyroJerkMagArCoeff_1"
		colnames(datMerge)[colnames(datMerge) == "V263"] <- "tBodyGyroJerkMagArCoeff_2"
		colnames(datMerge)[colnames(datMerge) == "V264"] <- "tBodyGyroJerkMagArCoeff_3"
		colnames(datMerge)[colnames(datMerge) == "V265"] <- "tBodyGyroJerkMagArCoeff_4"
		colnames(datMerge)[colnames(datMerge) == "V266"] <- "fBodyAccMeanX"
		colnames(datMerge)[colnames(datMerge) == "V267"] <- "fBodyAccMeanY"
		colnames(datMerge)[colnames(datMerge) == "V268"] <- "fBodyAccMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V269"] <- "fBodyAccStdX"
		colnames(datMerge)[colnames(datMerge) == "V270"] <- "fBodyAccStdY"
		colnames(datMerge)[colnames(datMerge) == "V271"] <- "fBodyAccStdZ"
		colnames(datMerge)[colnames(datMerge) == "V272"] <- "fBodyAccMadX"
		colnames(datMerge)[colnames(datMerge) == "V273"] <- "fBodyAccMadY"
		colnames(datMerge)[colnames(datMerge) == "V274"] <- "fBodyAccMadZ"
		colnames(datMerge)[colnames(datMerge) == "V275"] <- "fBodyAccMaxX"
		colnames(datMerge)[colnames(datMerge) == "V276"] <- "fBodyAccMaxY"
		colnames(datMerge)[colnames(datMerge) == "V277"] <- "fBodyAccMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V278"] <- "fBodyAccMinX"
		colnames(datMerge)[colnames(datMerge) == "V279"] <- "fBodyAccMinY"
		colnames(datMerge)[colnames(datMerge) == "V280"] <- "fBodyAccMinZ"
		colnames(datMerge)[colnames(datMerge) == "V281"] <- "fBodyAccSma"
		colnames(datMerge)[colnames(datMerge) == "V282"] <- "fBodyAccEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V283"] <- "fBodyAccEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V284"] <- "fBodyAccEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V285"] <- "fBodyAccIQRX"
		colnames(datMerge)[colnames(datMerge) == "V286"] <- "fBodyAccIQRY"
		colnames(datMerge)[colnames(datMerge) == "V287"] <- "fBodyAccIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V288"] <- "fBodyAccEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V289"] <- "fBodyAccEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V290"] <- "fBodyAccEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V291"] <- "fBodyAcc_maxInds_X"
		colnames(datMerge)[colnames(datMerge) == "V292"] <- "fBodyAcc_maxInds_Y"
		colnames(datMerge)[colnames(datMerge) == "V293"] <- "fBodyAcc_maxInds_Z"
		colnames(datMerge)[colnames(datMerge) == "V294"] <- "fBodyAcc_meanFreq_X"
		colnames(datMerge)[colnames(datMerge) == "V295"] <- "fBodyAcc_meanFreq_Y"
		colnames(datMerge)[colnames(datMerge) == "V296"] <- "fBodyAcc_meanFreq_Z"
		colnames(datMerge)[colnames(datMerge) == "V297"] <- "fBodyAcc_skewness_X"
		colnames(datMerge)[colnames(datMerge) == "V298"] <- "fBodyAcc_kurtosis_X"
		colnames(datMerge)[colnames(datMerge) == "V299"] <- "fBodyAcc_skewness_Y"
		colnames(datMerge)[colnames(datMerge) == "V300"] <- "fBodyAcc_kurtosis_Y"
		colnames(datMerge)[colnames(datMerge) == "V301"] <- "fBodyAcc_skewness_Z"
		colnames(datMerge)[colnames(datMerge) == "V302"] <- "fBodyAcc_kurtosis_Z"
		colnames(datMerge)[colnames(datMerge) == "V303"] <- "fBodyAcc_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V304"] <- "fBodyAcc_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V305"] <- "fBodyAcc_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V306"] <- "fBodyAcc_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V307"] <- "fBodyAcc_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V308"] <- "fBodyAcc_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V309"] <- "fBodyAcc_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V310"] <- "fBodyAcc_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V311"] <- "fBodyAcc_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V312"] <- "fBodyAcc_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V313"] <- "fBodyAcc_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V314"] <- "fBodyAcc_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V315"] <- "fBodyAcc_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V316"] <- "fBodyAcc_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V317"] <- "fBodyAcc_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V318"] <- "fBodyAcc_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V319"] <- "fBodyAcc_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V320"] <- "fBodyAcc_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V321"] <- "fBodyAcc_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V322"] <- "fBodyAcc_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V323"] <- "fBodyAcc_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V324"] <- "fBodyAcc_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V325"] <- "fBodyAcc_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V326"] <- "fBodyAcc_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V327"] <- "fBodyAcc_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V328"] <- "fBodyAcc_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V329"] <- "fBodyAcc_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V330"] <- "fBodyAcc_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V331"] <- "fBodyAcc_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V332"] <- "fBodyAcc_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V333"] <- "fBodyAcc_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V334"] <- "fBodyAcc_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V335"] <- "fBodyAcc_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V336"] <- "fBodyAcc_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V337"] <- "fBodyAcc_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V338"] <- "fBodyAcc_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V339"] <- "fBodyAcc_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V340"] <- "fBodyAcc_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V341"] <- "fBodyAcc_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V342"] <- "fBodyAcc_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V343"] <- "fBodyAcc_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V344"] <- "fBodyAcc_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V345"] <- "fBodyAccJerkMeanX"
		colnames(datMerge)[colnames(datMerge) == "V346"] <- "fBodyAccJerkMeanY"
		colnames(datMerge)[colnames(datMerge) == "V347"] <- "fBodyAccJerkMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V348"] <- "fBodyAccJerkStdX"
		colnames(datMerge)[colnames(datMerge) == "V349"] <- "fBodyAccJerkStdY"
		colnames(datMerge)[colnames(datMerge) == "V350"] <- "fBodyAccJerkStdZ"
		colnames(datMerge)[colnames(datMerge) == "V351"] <- "fBodyAccJerkMadX"
		colnames(datMerge)[colnames(datMerge) == "V352"] <- "fBodyAccJerkMadY"
		colnames(datMerge)[colnames(datMerge) == "V353"] <- "fBodyAccJerkMadZ"
		colnames(datMerge)[colnames(datMerge) == "V354"] <- "fBodyAccJerkMaxX"
		colnames(datMerge)[colnames(datMerge) == "V355"] <- "fBodyAccJerkMaxY"
		colnames(datMerge)[colnames(datMerge) == "V356"] <- "fBodyAccJerkMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V357"] <- "fBodyAccJerkMinX"
		colnames(datMerge)[colnames(datMerge) == "V358"] <- "fBodyAccJerkMinY"
		colnames(datMerge)[colnames(datMerge) == "V359"] <- "fBodyAccJerkMinZ"
		colnames(datMerge)[colnames(datMerge) == "V360"] <- "fBodyAccJerkSma"
		colnames(datMerge)[colnames(datMerge) == "V361"] <- "fBodyAccJerkEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V362"] <- "fBodyAccJerkEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V363"] <- "fBodyAccJerkEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V364"] <- "fBodyAccJerkIQRX"
		colnames(datMerge)[colnames(datMerge) == "V365"] <- "fBodyAccJerkIQRY"
		colnames(datMerge)[colnames(datMerge) == "V366"] <- "fBodyAccJerkIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V367"] <- "fBodyAccJerkEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V368"] <- "fBodyAccJerkEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V369"] <- "fBodyAccJerkEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V370"] <- "fBodyAccJerk_maxInds_X"
		colnames(datMerge)[colnames(datMerge) == "V371"] <- "fBodyAccJerk_maxInds_Y"
		colnames(datMerge)[colnames(datMerge) == "V372"] <- "fBodyAccJerk_maxInds_Z"
		colnames(datMerge)[colnames(datMerge) == "V373"] <- "fBodyAccJerk_meanFreq_X"
		colnames(datMerge)[colnames(datMerge) == "V374"] <- "fBodyAccJerk_meanFreq_Y"
		colnames(datMerge)[colnames(datMerge) == "V375"] <- "fBodyAccJerk_meanFreq_Z"
		colnames(datMerge)[colnames(datMerge) == "V376"] <- "fBodyAccJerk_skewness_X"
		colnames(datMerge)[colnames(datMerge) == "V377"] <- "fBodyAccJerk_kurtosis_X"
		colnames(datMerge)[colnames(datMerge) == "V378"] <- "fBodyAccJerk_skewness_Y"
		colnames(datMerge)[colnames(datMerge) == "V379"] <- "fBodyAccJerk_kurtosis_Y"
		colnames(datMerge)[colnames(datMerge) == "V380"] <- "fBodyAccJerk_skewness_Z"
		colnames(datMerge)[colnames(datMerge) == "V381"] <- "fBodyAccJerk_kurtosis_Z"
		colnames(datMerge)[colnames(datMerge) == "V382"] <- "fBodyAccJerk_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V383"] <- "fBodyAccJerk_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V384"] <- "fBodyAccJerk_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V385"] <- "fBodyAccJerk_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V386"] <- "fBodyAccJerk_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V387"] <- "fBodyAccJerk_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V388"] <- "fBodyAccJerk_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V389"] <- "fBodyAccJerk_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V390"] <- "fBodyAccJerk_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V391"] <- "fBodyAccJerk_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V392"] <- "fBodyAccJerk_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V393"] <- "fBodyAccJerk_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V394"] <- "fBodyAccJerk_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V395"] <- "fBodyAccJerk_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V396"] <- "fBodyAccJerk_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V397"] <- "fBodyAccJerk_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V398"] <- "fBodyAccJerk_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V399"] <- "fBodyAccJerk_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V400"] <- "fBodyAccJerk_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V401"] <- "fBodyAccJerk_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V402"] <- "fBodyAccJerk_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V403"] <- "fBodyAccJerk_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V404"] <- "fBodyAccJerk_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V405"] <- "fBodyAccJerk_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V406"] <- "fBodyAccJerk_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V407"] <- "fBodyAccJerk_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V408"] <- "fBodyAccJerk_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V409"] <- "fBodyAccJerk_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V410"] <- "fBodyAccJerk_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V411"] <- "fBodyAccJerk_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V412"] <- "fBodyAccJerk_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V413"] <- "fBodyAccJerk_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V414"] <- "fBodyAccJerk_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V415"] <- "fBodyAccJerk_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V416"] <- "fBodyAccJerk_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V417"] <- "fBodyAccJerk_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V418"] <- "fBodyAccJerk_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V419"] <- "fBodyAccJerk_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V420"] <- "fBodyAccJerk_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V421"] <- "fBodyAccJerk_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V422"] <- "fBodyAccJerk_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V423"] <- "fBodyAccJerk_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V424"] <- "fBodyGyroMeanX"
		colnames(datMerge)[colnames(datMerge) == "V425"] <- "fBodyGyroMeanY"
		colnames(datMerge)[colnames(datMerge) == "V426"] <- "fBodyGyroMeanZ"
		colnames(datMerge)[colnames(datMerge) == "V427"] <- "fBodyGyroStdX"
		colnames(datMerge)[colnames(datMerge) == "V428"] <- "fBodyGyroStdY"
		colnames(datMerge)[colnames(datMerge) == "V429"] <- "fBodyGyroStdZ"
		colnames(datMerge)[colnames(datMerge) == "V430"] <- "fBodyGyroMadX"
		colnames(datMerge)[colnames(datMerge) == "V431"] <- "fBodyGyroMadY"
		colnames(datMerge)[colnames(datMerge) == "V432"] <- "fBodyGyroMadZ"
		colnames(datMerge)[colnames(datMerge) == "V433"] <- "fBodyGyroMaxX"
		colnames(datMerge)[colnames(datMerge) == "V434"] <- "fBodyGyroMaxY"
		colnames(datMerge)[colnames(datMerge) == "V435"] <- "fBodyGyroMaxZ"
		colnames(datMerge)[colnames(datMerge) == "V436"] <- "fBodyGyroMinX"
		colnames(datMerge)[colnames(datMerge) == "V437"] <- "fBodyGyroMinY"
		colnames(datMerge)[colnames(datMerge) == "V438"] <- "fBodyGyroMinZ"
		colnames(datMerge)[colnames(datMerge) == "V439"] <- "fBodyGyroSma"
		colnames(datMerge)[colnames(datMerge) == "V440"] <- "fBodyGyroEnergyX"
		colnames(datMerge)[colnames(datMerge) == "V441"] <- "fBodyGyroEnergyY"
		colnames(datMerge)[colnames(datMerge) == "V442"] <- "fBodyGyroEnergyZ"
		colnames(datMerge)[colnames(datMerge) == "V443"] <- "fBodyGyroIQRX"
		colnames(datMerge)[colnames(datMerge) == "V444"] <- "fBodyGyroIQRY"
		colnames(datMerge)[colnames(datMerge) == "V445"] <- "fBodyGyroIQRZ"
		colnames(datMerge)[colnames(datMerge) == "V446"] <- "fBodyGyroEntropyX"
		colnames(datMerge)[colnames(datMerge) == "V447"] <- "fBodyGyroEntropyY"
		colnames(datMerge)[colnames(datMerge) == "V448"] <- "fBodyGyroEntropyZ"
		colnames(datMerge)[colnames(datMerge) == "V449"] <- "fBodyGyro_maxInds_X"
		colnames(datMerge)[colnames(datMerge) == "V450"] <- "fBodyGyro_maxInds_Y"
		colnames(datMerge)[colnames(datMerge) == "V451"] <- "fBodyGyro_maxInds_Z"
		colnames(datMerge)[colnames(datMerge) == "V452"] <- "fBodyGyro_meanFreq_X"
		colnames(datMerge)[colnames(datMerge) == "V453"] <- "fBodyGyro_meanFreq_Y"
		colnames(datMerge)[colnames(datMerge) == "V454"] <- "fBodyGyro_meanFreq_Z"
		colnames(datMerge)[colnames(datMerge) == "V455"] <- "fBodyGyro_skewness_X"
		colnames(datMerge)[colnames(datMerge) == "V456"] <- "fBodyGyro_kurtosis_X"
		colnames(datMerge)[colnames(datMerge) == "V457"] <- "fBodyGyro_skewness_Y"
		colnames(datMerge)[colnames(datMerge) == "V458"] <- "fBodyGyro_kurtosis_Y"
		colnames(datMerge)[colnames(datMerge) == "V459"] <- "fBodyGyro_skewness_Z"
		colnames(datMerge)[colnames(datMerge) == "V460"] <- "fBodyGyro_kurtosis_Z"
		colnames(datMerge)[colnames(datMerge) == "V461"] <- "fBodyGyro_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V462"] <- "fBodyGyro_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V463"] <- "fBodyGyro_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V464"] <- "fBodyGyro_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V465"] <- "fBodyGyro_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V466"] <- "fBodyGyro_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V467"] <- "fBodyGyro_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V468"] <- "fBodyGyro_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V469"] <- "fBodyGyro_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V470"] <- "fBodyGyro_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V471"] <- "fBodyGyro_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V472"] <- "fBodyGyro_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V473"] <- "fBodyGyro_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V474"] <- "fBodyGyro_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V475"] <- "fBodyGyro_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V476"] <- "fBodyGyro_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V477"] <- "fBodyGyro_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V478"] <- "fBodyGyro_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V479"] <- "fBodyGyro_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V480"] <- "fBodyGyro_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V481"] <- "fBodyGyro_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V482"] <- "fBodyGyro_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V483"] <- "fBodyGyro_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V484"] <- "fBodyGyro_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V485"] <- "fBodyGyro_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V486"] <- "fBodyGyro_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V487"] <- "fBodyGyro_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V488"] <- "fBodyGyro_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V489"] <- "fBodyGyro_bandsEnergy_1_8"
		colnames(datMerge)[colnames(datMerge) == "V490"] <- "fBodyGyro_bandsEnergy_9_16"
		colnames(datMerge)[colnames(datMerge) == "V491"] <- "fBodyGyro_bandsEnergy_17_24"
		colnames(datMerge)[colnames(datMerge) == "V492"] <- "fBodyGyro_bandsEnergy_25_32"
		colnames(datMerge)[colnames(datMerge) == "V493"] <- "fBodyGyro_bandsEnergy_33_40"
		colnames(datMerge)[colnames(datMerge) == "V494"] <- "fBodyGyro_bandsEnergy_41_48"
		colnames(datMerge)[colnames(datMerge) == "V495"] <- "fBodyGyro_bandsEnergy_49_56"
		colnames(datMerge)[colnames(datMerge) == "V496"] <- "fBodyGyro_bandsEnergy_57_64"
		colnames(datMerge)[colnames(datMerge) == "V497"] <- "fBodyGyro_bandsEnergy_1_16"
		colnames(datMerge)[colnames(datMerge) == "V498"] <- "fBodyGyro_bandsEnergy_17_32"
		colnames(datMerge)[colnames(datMerge) == "V499"] <- "fBodyGyro_bandsEnergy_33_48"
		colnames(datMerge)[colnames(datMerge) == "V500"] <- "fBodyGyro_bandsEnergy_49_64"
		colnames(datMerge)[colnames(datMerge) == "V501"] <- "fBodyGyro_bandsEnergy_1_24"
		colnames(datMerge)[colnames(datMerge) == "V502"] <- "fBodyGyro_bandsEnergy_25_48"
		colnames(datMerge)[colnames(datMerge) == "V503"] <- "fBodyAccMagMean"
		colnames(datMerge)[colnames(datMerge) == "V504"] <- "fBodyAccMagStd"
		colnames(datMerge)[colnames(datMerge) == "V505"] <- "fBodyAccMagMad"
		colnames(datMerge)[colnames(datMerge) == "V506"] <- "fBodyAccMagMax"
		colnames(datMerge)[colnames(datMerge) == "V507"] <- "fBodyAccMagMin"
		colnames(datMerge)[colnames(datMerge) == "V508"] <- "fBodyAccMagSma"
		colnames(datMerge)[colnames(datMerge) == "V509"] <- "fBodyAccMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V510"] <- "fBodyAccMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V511"] <- "fBodyAccMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V512"] <- "fBodyAccMag_maxInds"
		colnames(datMerge)[colnames(datMerge) == "V513"] <- "fBodyAccMag_meanFreq"
		colnames(datMerge)[colnames(datMerge) == "V514"] <- "fBodyAccMag_skewness"
		colnames(datMerge)[colnames(datMerge) == "V515"] <- "fBodyAccMag_kurtosis"
		colnames(datMerge)[colnames(datMerge) == "V516"] <- "fBodyBodyAccJerkMagMean"
		colnames(datMerge)[colnames(datMerge) == "V517"] <- "fBodyBodyAccJerkMagStd"
		colnames(datMerge)[colnames(datMerge) == "V518"] <- "fBodyBodyAccJerkMagMad"
		colnames(datMerge)[colnames(datMerge) == "V519"] <- "fBodyBodyAccJerkMagMax"
		colnames(datMerge)[colnames(datMerge) == "V520"] <- "fBodyBodyAccJerkMagMin"
		colnames(datMerge)[colnames(datMerge) == "V521"] <- "fBodyBodyAccJerkMagSma"
		colnames(datMerge)[colnames(datMerge) == "V522"] <- "fBodyBodyAccJerkMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V523"] <- "fBodyBodyAccJerkMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V524"] <- "fBodyBodyAccJerkMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V525"] <- "fBodyBodyAccJerkMag_maxInds"
		colnames(datMerge)[colnames(datMerge) == "V526"] <- "fBodyBodyAccJerkMag_meanFreq"
		colnames(datMerge)[colnames(datMerge) == "V527"] <- "fBodyBodyAccJerkMag_skewness"
		colnames(datMerge)[colnames(datMerge) == "V528"] <- "fBodyBodyAccJerkMag_kurtosis"
		colnames(datMerge)[colnames(datMerge) == "V529"] <- "fBodyBodyGyroMagMean"
		colnames(datMerge)[colnames(datMerge) == "V530"] <- "fBodyBodyGyroMagStd"
		colnames(datMerge)[colnames(datMerge) == "V531"] <- "fBodyBodyGyroMagMad"
		colnames(datMerge)[colnames(datMerge) == "V532"] <- "fBodyBodyGyroMagMax"
		colnames(datMerge)[colnames(datMerge) == "V533"] <- "fBodyBodyGyroMagMin"
		colnames(datMerge)[colnames(datMerge) == "V534"] <- "fBodyBodyGyroMagSma"
		colnames(datMerge)[colnames(datMerge) == "V535"] <- "fBodyBodyGyroMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V536"] <- "fBodyBodyGyroMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V537"] <- "fBodyBodyGyroMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V538"] <- "fBodyBodyGyroMag_maxInds"
		colnames(datMerge)[colnames(datMerge) == "V539"] <- "fBodyBodyGyroMag_meanFreq"
		colnames(datMerge)[colnames(datMerge) == "V540"] <- "fBodyBodyGyroMag_skewness"
		colnames(datMerge)[colnames(datMerge) == "V541"] <- "fBodyBodyGyroMag_kurtosis"
		colnames(datMerge)[colnames(datMerge) == "V542"] <- "fBodyBodyGyroJerkMagMean"
		colnames(datMerge)[colnames(datMerge) == "V543"] <- "fBodyBodyGyroJerkMagStd"
		colnames(datMerge)[colnames(datMerge) == "V544"] <- "fBodyBodyGyroJerkMagMad"
		colnames(datMerge)[colnames(datMerge) == "V545"] <- "fBodyBodyGyroJerkMagMax"
		colnames(datMerge)[colnames(datMerge) == "V546"] <- "fBodyBodyGyroJerkMagMin"
		colnames(datMerge)[colnames(datMerge) == "V547"] <- "fBodyBodyGyroJerkMagSma"
		colnames(datMerge)[colnames(datMerge) == "V548"] <- "fBodyBodyGyroJerkMagEnergy"
		colnames(datMerge)[colnames(datMerge) == "V549"] <- "fBodyBodyGyroJerkMag_iqr"
		colnames(datMerge)[colnames(datMerge) == "V550"] <- "fBodyBodyGyroJerkMagEntropy"
		colnames(datMerge)[colnames(datMerge) == "V551"] <- "fBodyBodyGyroJerkMag_maxInds"
		colnames(datMerge)[colnames(datMerge) == "V552"] <- "fBodyBodyGyroJerkMag_meanFreq"
		colnames(datMerge)[colnames(datMerge) == "V553"] <- "fBodyBodyGyroJerkMag_skewness"
		colnames(datMerge)[colnames(datMerge) == "V554"] <- "fBodyBodyGyroJerkMag_kurtosis"
		colnames(datMerge)[colnames(datMerge) == "V555"] <- "angle_tBodyAccMean_gravity"
		colnames(datMerge)[colnames(datMerge) == "V556"] <- "angle_tBodyAccJerkMean_gravityMean"
		colnames(datMerge)[colnames(datMerge) == "V557"] <- "angle_tBodyGyroMean_gravityMean"
		colnames(datMerge)[colnames(datMerge) == "V558"] <- "angle_tBodyGyroJerkMean_gravityMean"
		colnames(datMerge)[colnames(datMerge) == "V559"] <- "angle_X_gravityMean"
		colnames(datMerge)[colnames(datMerge) == "V560"] <- "angle_Y_gravityMean"
		colnames(datMerge)[colnames(datMerge) == "V561"] <- "angle_Z_gravityMean"
		
    
		##head(datMerge)
    
    ##Add a new column to hold the activity name with an initial value "INIT" that will be overwritten
		datMerge["ActivityName"] <- "INIT"
    
    
    ##head(datActivityLabels)

# 		ActivityId       ActivityName
# 		1          1            WALKING
# 		2          2   WALKING_UPSTAIRS
# 		3          3 WALKING_DOWNSTAIRS
# 		4          4            SITTING
# 		5          5           STANDING
# 		6          6             LAYING
    
    ##Update the ActivityName column using the Activity Labels corresponding values
		datMerge$ActivityName[datMerge$ActivityId == 1] <- "WALKING"
		datMerge$ActivityName[datMerge$ActivityId == 2] <- "WALKING_UPSTAIRS"
		datMerge$ActivityName[datMerge$ActivityId == 3] <- "WALKING_DOWNSTAIRS"
		datMerge$ActivityName[datMerge$ActivityId == 4] <- "SITTING"
		datMerge$ActivityName[datMerge$ActivityId == 5] <- "STANDING"
		datMerge$ActivityName[datMerge$ActivityId == 6] <- "LAYING"
    
		#datMerge$ActivityName <-  datActivityLabels [datMerge$ActivityId, 2] 
    
    #colnames(datMerge)    
    
    ##We need to subset out only the mean and std variables for the work so collect all them into a collection
		varsMeanAndStd <- c("tBodyAccMeanX","tBodyAccMeanY","tBodyAccMeanZ","tBodyAccStdX","tBodyAccStdY","tBodyAccStdZ","tGravityAccMeanX","tGravityAccMeanY","tGravityAccMeanZ","tGravityAccStdX","tGravityAccStdY","tGravityAccStdZ","tBodyAccJerkMeanX","tBodyAccJerkMeanY","tBodyAccJerkMeanZ","tBodyAccJerkStdX","tBodyAccJerkStdY","tBodyAccJerkStdZ","tBodyGyroMeanX","tBodyGyroMeanY","tBodyGyroMeanZ","tBodyGyroStdX","tBodyGyroStdY","tBodyGyroStdZ","tBodyGyroJerkMeanX","tBodyGyroJerkMeanY","tBodyGyroJerkMeanZ","tBodyGyroJerkStdX","tBodyGyroJerkStdY","tBodyGyroJerkStdZ","tBodyAccMagMean","tBodyAccMagStd","tGravityAccMagMean","tGravityAccMagStd","tBodyAccJerkMagMean","tBodyAccJerkMagStd","tBodyGyroMagMean","tBodyGyroMagStd","tBodyGyroJerkMagMean","tBodyGyroJerkMagStd","fBodyAccMeanX","fBodyAccMeanY","fBodyAccMeanZ","fBodyAccStdX","fBodyAccStdY","fBodyAccStdZ","fBodyAccJerkMeanX","fBodyAccJerkMeanY","fBodyAccJerkMeanZ","fBodyAccJerkStdX","fBodyAccJerkStdY","fBodyAccJerkStdZ","fBodyGyroMeanX","fBodyGyroMeanY","fBodyGyroMeanZ","fBodyGyroStdX","fBodyGyroStdY","fBodyGyroStdZ","fBodyAccMagMean","fBodyAccMagStd","fBodyBodyAccJerkMagMean","fBodyBodyAccJerkMagStd","fBodyBodyGyroMagMean","fBodyBodyGyroMagStd","fBodyBodyGyroJerkMagMean","fBodyBodyGyroJerkMagStd","angle_tBodyAccMean_gravity","angle_tBodyAccJerkMean_gravityMean","angle_tBodyGyroMean_gravityMean","angle_tBodyGyroJerkMean_gravityMean","angle_X_gravityMean","angle_Y_gravityMean","angle_Z_gravityMean", "Subject", "ActivityId", "ActivityName")
    ##subset the merge data and write to a new data table that only has the variables needed
		datMeanAndStd <- datMerge[varsMeanAndStd]
    
    ##head(datMeanAndStd)
    
		install.packages('reshape2')
    library(reshape2)
		install.packages('dplyr')
    library(dplyr)
    
    ##Transform the structure from a wide structure to a long structure to faciliate the processing    
		datTransform <- melt(datMeanAndStd, id.vars = c("Subject","ActivityName")) 
    
    ##head(datTransform)
		##tail(datTransform)
    
    ##Remove the ActivityId because the melt transformation inferred that it was a numeric value that needed to be transformed
		datTransform = datTransform[datTransform$variable !='ActivityId',]
    
		##Group the variables by Subject, Activity, and Variable
    datGroupByMeanAndStd <- group_by(datTransform, Subject, ActivityName, variable)
		##Now get the mean of the grouped values
    datCollapsedInMean <- summarise(datGroupByMeanAndStd, mean(value))
    
    ##Clean up the column names
		colnames(datCollapsedInMean)[colnames(datCollapsedInMean) == "mean(value)"] <- "MeanValue"
		colnames(datCollapsedInMean)[colnames(datCollapsedInMean) == "variable"] <- "Variable"
    
    ##head(datCollapsedInMean)
    ##tail(datCollapsedInMean)
    
    #Write out the resulting summarized data to a data file that can be distributed to others
		write.table(datCollapsedInMean, "C:/Training/GettingAndCleaning/Project/Data/UCI HAR Dataset/Output/GroupBySubjectActivityMeanVariables.txt", sep="\t",  row.name=FALSE)
